AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ProductName:
    Type: String
  Env:
    Type: String
    AllowedValues:
      - dev
      - stg
      - prd
  Name:
    Type: String

  VpcSecurityGroupIds:
    Type: CommaDelimitedList
  DBSubnetGroup:
    Type: String
  DBSecret:
    Type: String

Resources:
  DBCluster:
    Type: AWS::RDS::DBCluster
    DeletionPolicy: Delete # FIXME
    Properties:
      DBClusterIdentifier: !Ref Name
      DeletionProtection: true
      Engine: aurora-mysql
      EngineVersion: '8.0.mysql_aurora.3.02.0'
      # EngineMode:
      # DatabaseName:
      MasterUsername: !Join ['', ['{{resolve:secretsmanager:', !Ref DBSecret, ':SecretString:username}}' ]]
      MasterUserPassword: !Join ['', ['{{resolve:secretsmanager:', !Ref DBSecret, ':SecretString:password}}' ]]
      BackupRetentionPeriod: 7
      CopyTagsToSnapshot: true
      DBClusterParameterGroupName: !Ref DBClusterParameterGroup
      VpcSecurityGroupIds: !Ref VpcSecurityGroupIds
      DBSubnetGroupName: !Ref DBSubnetGroup
      StorageEncrypted: true
      PreferredBackupWindow: '04:00-05:00'
      PreferredMaintenanceWindow: 'mon:05:00-mon:07:00'
      RestoreType: full-copy
      Tags:
        - Key: 'ProductName'
          Value: !Ref ProductName
        - Key: 'Env'
          Value: !Ref Env
        - Key: 'Name'
          Value: !Ref Name

  DBClusterParameterGroup:
    Type: AWS::RDS::DBClusterParameterGroup
    Properties:
      Description: !Ref AWS::StackName
      Family: 'aurora-mysql8.0'
      Parameters:
          character_set_client: utf8mb4
          character_set_connection: utf8mb4
          character_set_database: utf8mb4
          character_set_results: utf8mb4
          character_set_filesystem: utf8mb4
          character_set_server: utf8mb4
          collation_connection: utf8mb4_bin
          collation_server: utf8mb4_bin
          skip-character-set-client-handshake: 1
          time_zone: Asia/Tokyo
      Tags:
        - Key: 'ProductName'
          Value: !Ref ProductName
        - Key: 'Env'
          Value: !Ref Env
        - Key: 'Name'
          Value: !Ref Name

Outputs:
  DBClusterId:
    Value: !Ref DBCluster
