AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ProductName:
    Type: String
  Env:
    Type: String
    AllowedValues:
      - dev
      - stg
      - prd
  Name:
    Type: String

  DBClusterId:
    Type: String
  DBSubnetGroupName:
    Type: String

Resources:
  DBInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Delete # FIXME
    Properties:
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: false
      # CopyTagsToSnapshot: true
      DBClusterIdentifier: !Ref DBClusterId
      DBInstanceClass: 'db.t3.medium'
      DBParameterGroupName: !Ref DBParameterGroup
      DBSubnetGroupName: !Ref DBSubnetGroupName
      Engine: 'aurora-mysql'
      Tags:
        - Key: 'ProductName'
          Value: !Ref ProductName
        - Key: 'Env'
          Value: !Ref Env
        - Key: 'Name'
          Value: !Ref Name

  DBParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: !Ref AWS::StackName
      Family: 'aurora-mysql8.0'
      Tags:
        - Key: 'ProductName'
          Value: !Ref ProductName
        - Key: 'Env'
          Value: !Ref Env
        - Key: 'Name'
          Value: !Ref Name
