AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ProductName:
    Type: String
  Env:
    Type: String
    AllowedValues:
      - dev
      - stg
      - prd
  Name:
    Type: String

  SubnetIds:
    Type: CommaDelimitedList

Resources:
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: !Ref AWS::StackName
      DBSubnetGroupName: !Sub ${Name}-db-subnet-group
      SubnetIds: !Ref SubnetIds
      Tags:
        - Key: 'ProductName'
          Value: !Ref ProductName
        - Key: 'Env'
          Value: !Ref Env
        - Key: 'Name'
          Value: !Ref Name

Outputs:
  DBSubnetGroupId:
    Value: !Ref DBSubnetGroup
