AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  ProductName:
    Type: String
  Env:
    Type: String
    AllowedValues:
      - dev
      - stg
      - prd
  Name:
    Type: String

  SubnetId:
    Type: String

Resources:
  Cloud9:
    Type: AWS::Cloud9::EnvironmentEC2
    DeletionPolicy: Delete # FIXME: DEV環境とそれ以外で分岐
    Properties:
      AutomaticStopTimeMinutes: 30
      ConnectionType: CONNECT_SSH
      Description: !Ref Name
      InstanceType: 't2.micro'
      Name: !Ref Name
      SubnetId: !Ref SubnetId
      Tags:
        - Key: 'ProductName'
          Value: !Ref ProductName
        - Key: 'Env'
          Value: !Ref Env

Outputs:
  Cloud9:
    Value: !Ref Cloud9
