AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  ProductName:
    Type: String
  Env:
    Type: String
    AllowedValues:
      - dev
      - stg
      - prd

Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    DeletionPolicy: Delete # FIXME: DEV環境とそれ以外で分岐
    Properties:
      ClusterName: !Sub ${ProductName}-cluster-${Env}
      Tags:
        - Key: 'ProductName'
          Value: !Ref ProductName
        - Key: 'Env'
          Value: !Ref Env

Outputs:
  ECSClusterArn:
    Value: !GetAtt ECSCluster.Arn
