AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  ProductName:
    Type: String
  Env:
    Type: String
    AllowedValues:
      - dev
      - stg
      - prd
  Name:
    Type: String

  ContainerCpu:
    Type: Number
  ContainerMemory:
    Type: Number
  ImageUrl:
    Type: String
  ContainerPort:
    Type: Number
  ExecutionRoleArn:
    Type: String
  TaskRoleArn:
    Type: String
  DBSecret:
    Type: String

Resources:
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    DeletionPolicy: Delete # FIXME: DEV環境とそれ以外で分岐
    Properties:
      Family: !Ref Name
      Cpu: !Ref ContainerCpu
      Memory: !Ref ContainerMemory
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !Ref ExecutionRoleArn
      TaskRoleArn: !Ref TaskRoleArn
      ContainerDefinitions:
        - Name: !Ref ProductName # コンテナ名
          Cpu: !Ref ContainerCpu
          Memory: !Ref ContainerMemory
          Image: !Ref ImageUrl
          PortMappings:
            - ContainerPort: !Ref ContainerPort
          Secrets:
            - Name: DB_HOST
              ValueFrom: !Join ['', [ !Ref DBSecret, ':host::' ]]
            - Name: DB_PORT
              ValueFrom: !Join ['', [ !Ref DBSecret, ':port::' ]]
            - Name: DB_USER
              ValueFrom: !Join ['', [ !Ref DBSecret, ':username::' ]]
            - Name: DB_PASS
              ValueFrom: !Join ['', [ !Ref DBSecret, ':password::' ]]
          # FIXME
          # LogConfiguration:
          #   LogDriver: awslogs
      Tags:
        - Key: 'ProductName'
          Value: !Ref ProductName
        - Key: 'Env'
          Value: !Ref Env
        - Key: 'Name'
          Value: !Ref Name

Outputs:
  TaskDefinitionArn:
    Value: !Ref TaskDefinition
