AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  ProductName:
    Type: String
  Env:
    Type: String
    AllowedValues:
      - dev
      - stg
      - prd

  ContainerCpu:
    Type: Number
  ContainerMemory:
    Type: Number
  ImageUrl:
    Type: String
  ContainerPort:
    Type: Number
  ExecutionRoleArn:
    Type: String

Resources:
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    DeletionPolicy: Delete # FIXME: DEV環境とそれ以外で分岐
    Properties:
      Family: !Sub ${ProductName}-service-${Env}
      Cpu: !Ref ContainerCpu
      Memory: !Ref ContainerMemory
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !Ref ExecutionRoleArn
      TaskRoleArn: !Ref AWS::NoValue
      ContainerDefinitions:
        - Name: !Sub ${ProductName}-service-${Env}
          Cpu: !Ref ContainerCpu
          Memory: !Ref ContainerMemory
          Image: !Ref ImageUrl
          PortMappings:
            - ContainerPort: !Ref ContainerPort
#          LogConfiguration:
#            LogDriver: awslogs

Outputs:
  TaskDefinitionArn:
    Value: !Ref TaskDefinition
