AWSTemplateFormatVersion: '2010-09-09'

# Lowercase letters
Parameters:
  #########################################
  # For Global
  #########################################
  ProductName:
    Type: String
  Env:
    Type: String
    AllowedValues:
      - dev
      - stg
      - prd

Resources:
  #########################################
  # VPC
  #########################################
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: '../../../templates/vpc/vpc.yml'
      Parameters:
        CidrBlock: '10.1.0.0/16'
        ProductName: !Ref ProductName
        Env: !Ref Env
        Name: !Sub ${ProductName}-vpc-${Env}

  #########################################
  # Subnet
  #########################################
  PublicSubnetA:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: '../../../templates/vpc/subnet.yml'
      Parameters:
        VPC: !GetAtt VPC.Outputs.VpcId
        CidrBlock: '10.1.0.0/24'
        AZ: 0
        ProductName: !Ref ProductName
        Env: !Ref Env
        Name: !Sub ${ProductName}-public-subnet-a-${Env}
  PublicSubnetC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: '../../../templates/vpc/subnet.yml'
      Parameters:
        VPC: !GetAtt VPC.Outputs.VpcId
        CidrBlock: '10.1.1.0/24'
        AZ: 1
        ProductName: !Ref ProductName
        Env: !Ref Env
        Name: !Sub ${ProductName}-public-subnet-c-${Env}
  PrivateSubnetA:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: '../../../templates/vpc/subnet.yml'
      Parameters:
        VPC: !GetAtt VPC.Outputs.VpcId
        CidrBlock: '10.1.8.0/24'
        AZ: 0
        ProductName: !Ref ProductName
        Env: !Ref Env
        Name: !Sub ${ProductName}-private-subnet-a-${Env}
  PrivateSubnetC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: '../../../templates/vpc/subnet.yml'
      Parameters:
        VPC: !GetAtt VPC.Outputs.VpcId
        CidrBlock: '10.1.9.0/24'
        AZ: 1
        ProductName: !Ref ProductName
        Env: !Ref Env
        Name: !Sub ${ProductName}-private-subnet-c-${Env}
  PrivateSubnetAForDB:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: '../../../templates/vpc/subnet.yml'
      Parameters:
        VPC: !GetAtt VPC.Outputs.VpcId
        CidrBlock: '10.1.16.0/24'
        AZ: 0
        ProductName: !Ref ProductName
        Env: !Ref Env
        Name: !Sub ${ProductName}-private-subnet-a-db-${Env}
  PrivateSubnetCForDB:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: '../../../templates/vpc/subnet.yml'
      Parameters:
        VPC: !GetAtt VPC.Outputs.VpcId
        CidrBlock: '10.1.17.0/24'
        AZ: 1
        ProductName: !Ref ProductName
        Env: !Ref Env
        Name: !Sub ${ProductName}-private-subnet-c-db-${Env}
  PublicSubnetAForCloud9:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: '../../../templates/vpc/subnet.yml'
      Parameters:
        VPC: !GetAtt VPC.Outputs.VpcId
        CidrBlock: '10.1.240.0/24'
        AZ: 0
        ProductName: !Ref ProductName
        Env: !Ref Env
        Name: !Sub ${ProductName}-private-subnet-a-cloud9-${Env}
  PublicSubnetCForCloud9:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: '../../../templates/vpc/subnet.yml'
      Parameters:
        VPC: !GetAtt VPC.Outputs.VpcId
        CidrBlock: '10.1.241.0/24'
        AZ: 1
        ProductName: !Ref ProductName
        Env: !Ref Env
        Name: !Sub ${ProductName}-private-subnet-a-cloud9-${Env}
  PrivateSubnetAForVPCEndpoint:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: '../../../templates/vpc/subnet.yml'
      Parameters:
        VPC: !GetAtt VPC.Outputs.VpcId
        CidrBlock: '10.1.248.0/24'
        AZ: 0
        ProductName: !Ref ProductName
        Env: !Ref Env
        Name: !Sub ${ProductName}-private-subnet-a-vpcendpoint-${Env}
  PrivateSubnetCForVPCEndpoint:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: '../../../templates/vpc/subnet.yml'
      Parameters:
        VPC: !GetAtt VPC.Outputs.VpcId
        CidrBlock: '10.1.249.0/24'
        AZ: 1
        ProductName: !Ref ProductName
        Env: !Ref Env
        Name: !Sub ${ProductName}-private-subnet-c-vpcendpoint-${Env}

  #########################################
  # InternetGateway
  # ✗ nested stack
  #########################################
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: 'ProductName'
          Value: !Ref ProductName
        - Key: 'Env'
          Value: !Ref Env
        - Key: 'Name'
          Value: !Sub internet-gateway-${Env}
  GatewayAttachement:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !GetAtt VPC.Outputs.VpcId
      InternetGatewayId: !Ref InternetGateway

  #########################################
  # RouteTable For PublicSubnet（IGW）
  #########################################
  PublicRouteTable:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: '../../../templates/vpc/route_table.yml'
      Parameters:
        VPC: !GetAtt VPC.Outputs.VpcId
        ProductName: !Ref ProductName
        Env: !Ref Env
        Name: !Sub ${ProductName}-public-route-table-${Env}
  PublicRoute:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: '../../../templates/vpc/route.yml'
      Parameters:
        RouteTableId: !GetAtt PublicRouteTable.Outputs.RouteTable
        GatewayId: !Ref InternetGateway
        NatGatewayId: ''
  PublicSubnetARouteTableAssociation:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: '../../../templates/vpc/route_table_associate.yml'
      Parameters:
        SubnetId: !GetAtt PublicSubnetA.Outputs.SubnetId
        RouteTableId: !GetAtt PublicRouteTable.Outputs.RouteTable
  PublicSubnetCRouteTableAssociation:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: '../../../templates/vpc/route_table_associate.yml'
      Parameters:
        SubnetId: !GetAtt PublicSubnetC.Outputs.SubnetId
        RouteTableId: !GetAtt PublicRouteTable.Outputs.RouteTable
  PublicSubnetAForCloud9RouteTableAssociation:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: '../../../templates/vpc/route_table_associate.yml'
      Parameters:
        SubnetId: !GetAtt PublicSubnetAForCloud9.Outputs.SubnetId
        RouteTableId: !GetAtt PublicRouteTable.Outputs.RouteTable
  PublicSubnetCForCloud9RouteTableAssociation:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: '../../../templates/vpc/route_table_associate.yml'
      Parameters:
        SubnetId: !GetAtt PublicSubnetCForCloud9.Outputs.SubnetId
        RouteTableId: !GetAtt PublicRouteTable.Outputs.RouteTable

  #########################################
  # RouteTable For ECS VPCEndpoint（Gateway）
  # TODO: このルートテーブルどうなってるか見ておく
  #########################################
  RouteTableForECSVPCEndpoint:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: '../../../templates/vpc/route_table.yml'
      Parameters:
        VPC: !GetAtt VPC.Outputs.VpcId
        ProductName: !Ref ProductName
        Env: !Ref Env
        Name: !Sub ${ProductName}-route-table-for-ecs-vpcendpoint-${Env}
  PrivateSubnetARouteTableForECSVPCEndpointAssociation:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: '../../../templates/vpc/route_table_associate.yml'
      Parameters:
        SubnetId: !GetAtt PrivateSubnetA.Outputs.SubnetId
        RouteTableId: !GetAtt RouteTableForECSVPCEndpoint.Outputs.RouteTable
  PrivateSubnetCRouteTableForECSVPCEndpointAssociation:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: '../../../templates/vpc/route_table_associate.yml'
      Parameters:
        SubnetId: !GetAtt PrivateSubnetC.Outputs.SubnetId
        RouteTableId: !GetAtt RouteTableForECSVPCEndpoint.Outputs.RouteTable

  #########################################
  # RouteTable For Database
  # TODO: このルートテーブルどうなってるか見ておく
  #########################################
  RouteTableForDB:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: '../../../templates/vpc/route_table.yml'
      Parameters:
        VPC: !GetAtt VPC.Outputs.VpcId
        ProductName: !Ref ProductName
        Env: !Ref Env
        Name: !Sub ${ProductName}-route-table-for-db-${Env}
  PrivateSubnetARouteTableForDBAssociation:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: '../../../templates/vpc/route_table_associate.yml'
      Parameters:
        SubnetId: !GetAtt PrivateSubnetAForDB.Outputs.SubnetId
        RouteTableId: !GetAtt RouteTableForDB.Outputs.RouteTable
  PrivateSubnetCRouteTableForDBAssociation:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: '../../../templates/vpc/route_table_associate.yml'
      Parameters:
        SubnetId: !GetAtt PrivateSubnetCForDB.Outputs.SubnetId
        RouteTableId: !GetAtt RouteTableForDB.Outputs.RouteTable

  #########################################
  # NATGateway
  # EIPでPrivateSubnet内のリソースにアクセスする用
  # PrivateSubnetへの通信はALBのみに制限するのが、よりセキュア 特に用がないなら削除推奨
  # NatGatewayは取り外し
  #########################################
  #  NatGatewayA:
  #    Type: AWS::CloudFormation::Stack
  #    Properties:
  #      TemplateURL: '../../templates/vpc/nat_gateway.yml'
  #      Parameters:
  #        SubnetId: !GetAtt PublicSubnetA.Outputs.SubnetId
  #        ProductName: !Ref ProductName
  #        Env: !Ref Env
  #  NatGatewayC:
  #    Type: AWS::CloudFormation::Stack
  #    Properties:
  #      TemplateURL: '../../templates/vpc/nat_gateway.yml'
  #      Parameters:
  #        SubnetId: !GetAtt PublicSubnetC.Outputs.SubnetId
  #        ProductName: !Ref ProductName
  #        Env: !Ref Env

  #########################################
  # PrivateRouteTable
  # NatGateway取り外し
  # route tableってAとCで2ついるっけ...？
  #########################################
  #  PrivateRouteTableA:
  #    Type: AWS::CloudFormation::Stack
  #    Properties:
  #      TemplateURL: '../../templates/vpc/route_table.yml'
  #      Parameters:
  #        VPC: !GetAtt VPC.Outputs.VpcId
  #        ProductName: !Ref ProductName
  #        Env: !Ref Env
  #        Name: !Sub ${ProductName}-${Env}-private-route-table-a
  #  PrivateRouteA:
  #    Type: AWS::CloudFormation::Stack
  #    Properties:
  #      TemplateURL: '../../templates/vpc/route.yml'
  #      Parameters:
  #        RouteTableId: PrivateRouteTableA.Outputs.RouteTable
  #        GatewayId: ''
  #        NatGatewayId: !GetAtt NatGatewayA.Outputs.NatGateway
  #  PrivateSubnetARouteTableAssociation:
  #    Type: AWS::CloudFormation::Stack
  #    Properties:
  #      TemplateURL: '../../templates/vpc/route_table_associate.yml'
  #      Parameters:
  #        SubnetId: !GetAtt PrivateSubnetA.Outputs.SubnetId
  #        RouteTableId: !GetAtt PrivateRouteTableA.Outputs.RouteTable
  #  PrivateRouteTableC:
  #    Type: AWS::CloudFormation::Stack
  #    Properties:
  #      TemplateURL: '../../templates/vpc/route_table.yml'
  #      Parameters:
  #        VPC: !GetAtt VPC.Outputs.VpcId
  #        ProductName: !Ref ProductName
  #        Env: !Ref Env
  #        Name: !Sub ${ProductName}-${Env}-private-route-table-a
  #  PrivateRouteC:
  #    Type: AWS::CloudFormation::Stack
  #    Properties:
  #      TemplateURL: '../../templates/vpc/route.yml'
  #      Parameters:
  #        RouteTableId: PrivateRouteTableA.Outputs.RouteTable
  #        GatewayId: ''
  #        NatGatewayId: !GetAtt NatGatewayC.Outputs.NatGateway
  #  PrivateSubnetCRouteTableAssociation:
  #    Type: AWS::CloudFormation::Stack
  #    Properties:
  #      TemplateURL: '../../templates/vpc/route_table_associate.yml'
  #      Parameters:
  #        SubnetId: !GetAtt PrivateSubnetC.Outputs.SubnetId
  #        RouteTableId: !GetAtt PrivateRouteTableC.Outputs.RouteTable

Outputs:
  VPC:
    Value: !GetAtt VPC.Outputs.VpcId
    Export:
      Name: VPC
  PublicSubnetA:
    Value: !GetAtt PublicSubnetA.Outputs.SubnetId
    Export:
      Name: PublicSubnetA
  PublicSubnetC:
    Value: !GetAtt PublicSubnetC.Outputs.SubnetId
    Export:
      Name: PublicSubnetC
  PrivateSubnetA:
    Value: !GetAtt PrivateSubnetA.Outputs.SubnetId
    Export:
      Name: PrivateSubnetA
  PrivateSubnetC:
    Value: !GetAtt PrivateSubnetC.Outputs.SubnetId
    Export:
      Name: PrivateSubnetC
  PrivateSubnetAForDB:
    Value: !GetAtt PrivateSubnetAForDB.Outputs.SubnetId
    Export:
      Name: PrivateSubnetAForDB
  PrivateSubnetCForDB:
    Value: !GetAtt PrivateSubnetCForDB.Outputs.SubnetId
    Export:
      Name: PrivateSubnetCForDB
  PublicSubnetAForCloud9:
    Value: !GetAtt PublicSubnetAForCloud9.Outputs.SubnetId
    Export:
      Name: PublicSubnetAForCloud9
  PublicSubnetCForCloud9: # AZ-a障害時の予備
    Value: !GetAtt PublicSubnetCForCloud9.Outputs.SubnetId
    Export:
      Name: PublicSubnetCForCloud9
  PrivateSubnetAForVPCEndpoint:
    Value: !GetAtt PrivateSubnetAForVPCEndpoint.Outputs.SubnetId
    Export:
      Name: PrivateSubnetAForVPCEndpoint
  PrivateSubnetCForVPCEndpoint:
    Value: !GetAtt PrivateSubnetCForVPCEndpoint.Outputs.SubnetId
    Export:
      Name: PrivateSubnetCForVPCEndpoint
  RouteTableForECSVPCEndpoint:
    Value: !GetAtt RouteTableForECSVPCEndpoint.Outputs.RouteTable
    Export:
      Name: RouteTableForECSVPCEndpoint
