AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  ProductName:
    Type: String
  Env:
    Type: String
    AllowedValues:
      - dev
      - stg
      - prd

Resources:
  #########################################
  # Aurora Cluster（MySQL）
  #########################################
  DBSubnetGroup:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: '../../../../templates/rds/subnet_group.yml'
      Parameters:
        SubnetIds: !Join [ ',', [!ImportValue PrivateSubnetAForDB, !ImportValue PrivateSubnetCForDB] ]
        ProductName: !Ref ProductName
        Env: !Ref Env
        Name: !Sub ${ProductName}-db-subnet-group-${Env}
  ResourceDBCluster:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: '../../../../templates/rds/cluster.yml'
      Parameters:
        VpcSecurityGroupIds: !Join [ ',', [!ImportValue DBSecurityGroup] ]
        DBSubnetGroup: !GetAtt DBSubnetGroup.Outputs.DBSubnetGroupId
        DBSecret: !GetAtt RDBSecrets.Outputs.SecretId
        ProductName: !Ref ProductName
        Env: !Ref Env
        Name: !Sub ${ProductName}-resource-db-cluster-${Env}
  ResourceDBInstanceA:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: '../../../../templates/rds/instance.yml'
      Parameters:
        DBClusterId: !GetAtt ResourceDBCluster.Outputs.DBClusterId
        DBSubnetGroupName: !GetAtt DBSubnetGroup.Outputs.DBSubnetGroupId
        ProductName: !Ref ProductName
        Env: !Ref Env
        Name: !Sub ${ProductName}-resource-db-a-${Env}
  ResourceDBInstanceC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: '../../../../templates/rds/instance.yml'
      Parameters:
        DBClusterId: !GetAtt ResourceDBCluster.Outputs.DBClusterId
        DBSubnetGroupName: !GetAtt DBSubnetGroup.Outputs.DBSubnetGroupId
        ProductName: !Ref ProductName
        Env: !Ref Env
        Name: !Sub ${ProductName}-resource-db-c-${Env}

  #########################################
  # Secrets Manager（ResourceDB）
  #########################################
  RDBSecrets:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: '../../../../templates/secrets_manager/secret.yml'
      Parameters:
        ProductName: !Ref ProductName
        Env: !Ref Env
        Name: !Sub ${ProductName}-resource-db-${Env}
  RDBSecretsRotate:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: '../../../../templates/secrets_manager/rotation_schedule.yml'
      Parameters:
        SecretId: !GetAtt RDBSecrets.Outputs.SecretId
        AutomaticallyAfterDays: 1 # FIXME
        Duration: 1h
  RDBSecretsAttachment:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: '../../../../templates/secrets_manager/target_attachment.yml'
      Parameters:
        SecretId: !GetAtt RDBSecrets.Outputs.SecretId
        TargetId: !GetAtt ResourceDBCluster.Outputs.DBClusterId

Outputs:
  RDBSecrets:
    Value: !GetAtt RDBSecrets.Outputs.SecretId
    Export:
      Name: RDBSecrets
