AWSTemplateFormatVersion: '2010-09-09'
Description: >
  VPC,Subnet,NATGateway,RouteTable

Parameters:
  ProductName:
    Type: String
  Env:
    Type: String
    AllowedValues:
      - dev
      - stg
      - prd

Resources:
  #########################################
  # VPC
  #########################################
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: '../../templates/vpc/vpc.yml'
      Parameters:
        CidrBlock: '10.0.0.0/16'
        ProductName: !Ref ProductName
        Env: !Ref Env

  #########################################
  # Subnet
  #########################################
  PublicSubnetA:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: '../../templates/vpc/subnet.yml'
      Parameters:
        VPC: !GetAtt VPC.Outputs.VpcId
        CidrBlock: '10.0.0.0/24'
        AZ: 0
        ProductName: !Ref ProductName
        Env: !Ref Env
  PublicSubnetC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: '../../templates/vpc/subnet.yml'
      Parameters:
        VPC: !GetAtt VPC.Outputs.VpcId
        CidrBlock: '10.0.1.0/24'
        AZ: 2
        ProductName: !Ref ProductName
        Env: !Ref Env
  PrivateSubnetA:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: '../../templates/vpc/subnet.yml'
      Parameters:
        VPC: !GetAtt VPC.Outputs.VpcId
        CidrBlock: '10.0.8.0/24'
        AZ: 0
        ProductName: !Ref ProductName
        Env: !Ref Env
  PrivateSubnetC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: '../../templates/vpc/subnet.yml'
      Parameters:
        VPC: !GetAtt VPC.Outputs.VpcId
        CidrBlock: '10.0.9.0/24'
        AZ: 2
        ProductName: !Ref ProductName
        Env: !Ref Env
  PrivateSubnetAForDB:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: '../../templates/vpc/subnet.yml'
      Parameters:
        VPC: !GetAtt VPC.Outputs.VpcId
        CidrBlock: '10.0.16.0/24'
        AZ: 0
        ProductName: !Ref ProductName
        Env: !Ref Env
  PrivateSubnetCForDB:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: '../../templates/vpc/subnet.yml'
      Parameters:
        VPC: !GetAtt VPC.Outputs.VpcId
        CidrBlock: '10.0.17.0/24'
        AZ: 1
        ProductName: !Ref ProductName
        Env: !Ref Env
  PublicSubnetAForBastion:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: '../../templates/vpc/subnet.yml'
      Parameters:
        VPC: !GetAtt VPC.Outputs.VpcId
        CidrBlock: '10.0.240.0/24'
        AZ: 0
        ProductName: !Ref ProductName
        Env: !Ref Env
  PublicSubnetCForBastion:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: '../../templates/vpc/subnet.yml'
      Parameters:
        VPC: !GetAtt VPC.Outputs.VpcId
        CidrBlock: '10.0.241.0/24'
        AZ: 1
        ProductName: !Ref ProductName
        Env: !Ref Env
  PrivateSubnetAForVPCEndpoint:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: '../../templates/vpc/subnet.yml'
      Parameters:
        VPC: !GetAtt VPC.Outputs.VpcId
        CidrBlock: '10.0.248.0/24'
        AZ: 0
        ProductName: !Ref ProductName
        Env: !Ref Env
  PrivateSubnetCForVPCEndpoint:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: '../../templates/vpc/subnet.yml'
      Parameters:
        VPC: !GetAtt VPC.Outputs.VpcId
        CidrBlock: '10.0.249.0/24'
        AZ: 1
        ProductName: !Ref ProductName
        Env: !Ref Env


  #########################################
  # InternetGateway
  # ✗ nested stack
  #########################################
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: 'ProductName'
          Value: !Ref ProductName
        - Key: 'Env'
          Value: !Ref Env
  GatewayAttachement:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !GetAtt VPC.Outputs.VpcId
      InternetGatewayId: !Ref InternetGateway

  #########################################
  # PublicRouteTable
  #########################################
  PublicRouteTable:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: '../../templates/vpc/route_table.yml'
      Parameters:
        VPC: !GetAtt VPC.Outputs.VpcId
        ProductName: !Ref ProductName
        Env: !Ref Env
  PublicRoute:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: '../../templates/vpc/route.yml'
      Parameters:
        GatewayId: !Ref InternetGateway
        NatGatewayId: ''
  PublicSubnetARouteTableAssociation:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: '../../templates/vpc/route_table_associate.yml'
      Parameters:
        SubnetId: !GetAtt PublicSubnetA.Outputs.SubnetId
        RouteTableId: !GetAtt PublicRouteTable.Outputs.RouteTable
        ProductName: !Ref ProductName
        Env: !Ref Env
  PublicSubnetCRouteTableAssociation:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: '../../templates/vpc/route_table_associate.yml'
      Parameters:
        SubnetId: !GetAtt PublicSubnetC.Outputs.SubnetId
        RouteTableId: !GetAtt PublicRouteTable.Outputs.RouteTable
        ProductName: !Ref ProductName
        Env: !Ref Env

Outputs:
  VPC:
    Value: !GetAtt VPC.Outputs.VpcId
    Export:
      Name: VPC
  PublicSubnetA:
    Value: !GetAtt PublicSubnetA.Outputs.SubnetId
    Export:
      Name: PublicSubnetA
  PublicSubnetC:
    Value: !GetAtt PublicSubnetC.Outputs.SubnetId
    Export:
      Name: PublicSubnetC
  PrivateSubnetA:
    Value: !GetAtt PrivateSubnetA.Outputs.SubnetId
    Export:
      Name: PrivateSubnetA
  PrivateSubnetC:
    Value: !GetAtt PrivateSubnetC.Outputs.SubnetId
    Export:
      Name: PrivateSubnetC
  PrivateSubnetAForDB:
    Value: !GetAtt PrivateSubnetAForDB.Outputs.SubnetId
    Export:
      Name: PrivateSubnetAForDB
  PrivateSubnetCForDB:
    Value: !GetAtt PrivateSubnetCForDB.Outputs.SubnetId
    Export:
      Name: PrivateSubnetCForDB
  PublicSubnetAForBastion:
    Value: !GetAtt PublicSubnetAForBastion.Outputs.SubnetId
    Export:
      Name: PublicSubnetAForBastion
  PublicSubnetCForBastion:
    Value: !GetAtt PublicSubnetCForBastion.Outputs.SubnetId
    Export:
      Name: PublicSubnetCForBastion
  PrivateSubnetAForVPCEndpoint:
    Value: !GetAtt PrivateSubnetAForVPCEndpoint.Outputs.SubnetId
    Export:
      Name: PrivateSubnetAForVPCEndpoint
  PrivateSubnetCForVPCEndpoint:
    Value: !GetAtt PrivateSubnetCForVPCEndpoint.Outputs.SubnetId
    Export:
      Name: PrivateSubnetCForVPCEndpoint
