AWSTemplateFormatVersion: '2010-09-09'
Description: >
  VPC,Subnet,NATGateway,RouteTable

# Lowercase letters
Parameters:
  ProductName:
    Type: String
  Env:
    Type: String
    AllowedValues:
      - dev
      - stg
      - prd

Resources:
  #########################################
  # VPC
  #########################################
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: '../../templates/vpc/vpc.yml'
      Parameters:
        CidrBlock: '10.1.0.0/16'
        ProductName: !Ref ProductName
        Env: !Ref Env
        Name: !Sub vpc-${Env}

  #########################################
  # Subnet
  #########################################
  PublicSubnetA:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: '../../templates/vpc/subnet.yml'
      Parameters:
        VPC: !GetAtt VPC.Outputs.VpcId
        CidrBlock: '10.1.0.0/24'
        AZ: 0
        ProductName: !Ref ProductName
        Env: !Ref Env
        Name: !Sub public-subnet-a-${Env}
  PublicSubnetC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: '../../templates/vpc/subnet.yml'
      Parameters:
        VPC: !GetAtt VPC.Outputs.VpcId
        CidrBlock: '10.1.1.0/24'
        AZ: 2
        ProductName: !Ref ProductName
        Env: !Ref Env
        Name: !Sub public-subnet-c-${Env}
  PrivateSubnetA:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: '../../templates/vpc/subnet.yml'
      Parameters:
        VPC: !GetAtt VPC.Outputs.VpcId
        CidrBlock: '10.1.8.0/24'
        AZ: 0
        ProductName: !Ref ProductName
        Env: !Ref Env
        Name: !Sub private-subnet-a-${Env}
  PrivateSubnetC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: '../../templates/vpc/subnet.yml'
      Parameters:
        VPC: !GetAtt VPC.Outputs.VpcId
        CidrBlock: '10.1.9.0/24'
        AZ: 2
        ProductName: !Ref ProductName
        Env: !Ref Env
        Name: !Sub private-subnet-c-${Env}
  PrivateSubnetAForDB:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: '../../templates/vpc/subnet.yml'
      Parameters:
        VPC: !GetAtt VPC.Outputs.VpcId
        CidrBlock: '10.1.16.0/24'
        AZ: 0
        ProductName: !Ref ProductName
        Env: !Ref Env
        Name: !Sub private-subnet-a-db-${Env}
  PrivateSubnetCForDB:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: '../../templates/vpc/subnet.yml'
      Parameters:
        VPC: !GetAtt VPC.Outputs.VpcId
        CidrBlock: '10.1.17.0/24'
        AZ: 1
        ProductName: !Ref ProductName
        Env: !Ref Env
        Name: !Sub private-subnet-c-db-${Env}
  PublicSubnetAForCloud9:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: '../../templates/vpc/subnet.yml'
      Parameters:
        VPC: !GetAtt VPC.Outputs.VpcId
        CidrBlock: '10.1.240.0/24'
        AZ: 0
        ProductName: !Ref ProductName
        Env: !Ref Env
        Name: !Sub private-subnet-a-cloud9-${Env}
  PublicSubnetCForCloud9:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: '../../templates/vpc/subnet.yml'
      Parameters:
        VPC: !GetAtt VPC.Outputs.VpcId
        CidrBlock: '10.1.241.0/24'
        AZ: 1
        ProductName: !Ref ProductName
        Env: !Ref Env
        Name: !Sub private-subnet-a-cloud9-${Env}
  PrivateSubnetAForVPCEndpoint:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: '../../templates/vpc/subnet.yml'
      Parameters:
        VPC: !GetAtt VPC.Outputs.VpcId
        CidrBlock: '10.1.248.0/24'
        AZ: 0
        ProductName: !Ref ProductName
        Env: !Ref Env
        Name: !Sub private-subnet-a-vpcendpoint-${Env}
  PrivateSubnetCForVPCEndpoint:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: '../../templates/vpc/subnet.yml'
      Parameters:
        VPC: !GetAtt VPC.Outputs.VpcId
        CidrBlock: '10.1.249.0/24'
        AZ: 1
        ProductName: !Ref ProductName
        Env: !Ref Env
        Name: !Sub private-subnet-c-vpcendpoint-${Env}

  #########################################
  # InternetGateway
  # ✗ nested stack
  #########################################
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: 'ProductName'
          Value: !Ref ProductName
        - Key: 'Env'
          Value: !Ref Env
        - Key: 'Name'
          Value: !Sub internet-gateway-${Env}
  GatewayAttachement:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !GetAtt VPC.Outputs.VpcId
      InternetGatewayId: !Ref InternetGateway

  #########################################
  # PublicRouteTable
  #########################################
  PublicRouteTable:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: '../../templates/vpc/route_table.yml'
      Parameters:
        VPC: !GetAtt VPC.Outputs.VpcId
        ProductName: !Ref ProductName
        Env: !Ref Env
        Name: !Sub public-route-table-${Env}
  PublicRoute:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: '../../templates/vpc/route.yml'
      Parameters:
        RouteTableId: !GetAtt PublicRouteTable.Outputs.RouteTable
        GatewayId: !Ref InternetGateway
        NatGatewayId: ''
  PublicSubnetARouteTableAssociation:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: '../../templates/vpc/route_table_associate.yml'
      Parameters:
        SubnetId: !GetAtt PublicSubnetA.Outputs.SubnetId
        RouteTableId: !GetAtt PublicRouteTable.Outputs.RouteTable
  PublicSubnetCRouteTableAssociation:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: '../../templates/vpc/route_table_associate.yml'
      Parameters:
        SubnetId: !GetAtt PublicSubnetC.Outputs.SubnetId
        RouteTableId: !GetAtt PublicRouteTable.Outputs.RouteTable

Outputs:
  VPC:
    Value: !GetAtt VPC.Outputs.VpcId
    Export:
      Name: VPC
  PublicSubnetA:
    Value: !GetAtt PublicSubnetA.Outputs.SubnetId
    Export:
      Name: PublicSubnetA
  PublicSubnetC:
    Value: !GetAtt PublicSubnetC.Outputs.SubnetId
    Export:
      Name: PublicSubnetC
  PrivateSubnetA:
    Value: !GetAtt PrivateSubnetA.Outputs.SubnetId
    Export:
      Name: PrivateSubnetA
  PrivateSubnetC:
    Value: !GetAtt PrivateSubnetC.Outputs.SubnetId
    Export:
      Name: PrivateSubnetC
  PrivateSubnetAForDB:
    Value: !GetAtt PrivateSubnetAForDB.Outputs.SubnetId
    Export:
      Name: PrivateSubnetAForDB
  PrivateSubnetCForDB:
    Value: !GetAtt PrivateSubnetCForDB.Outputs.SubnetId
    Export:
      Name: PrivateSubnetCForDB
  PublicSubnetAForCloud9:
    Value: !GetAtt PublicSubnetAForCloud9.Outputs.SubnetId
    Export:
      Name: PublicSubnetAForCloud9
  PublicSubnetCForCloud9:
    Value: !GetAtt PublicSubnetCForCloud9.Outputs.SubnetId
    Export:
      Name: PublicSubnetCForCloud9
  PrivateSubnetAForVPCEndpoint:
    Value: !GetAtt PrivateSubnetAForVPCEndpoint.Outputs.SubnetId
    Export:
      Name: PrivateSubnetAForVPCEndpoint
  PrivateSubnetCForVPCEndpoint:
    Value: !GetAtt PrivateSubnetCForVPCEndpoint.Outputs.SubnetId
    Export:
      Name: PrivateSubnetCForVPCEndpoint
