AWSTemplateFormatVersion: '2010-09-09'
Description: "VPC,Subnet,NATGateway,RouteTable\n"
Parameters:
  ProductName:
    Type: String
  Env:
    Type: String
    AllowedValues:
    - dev
    - stg
    - prd
Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-northeast-1.amazonaws.com/cfn-template-myproduct-dev/network/abce44712e1428720bcce5a496398471.template
      Parameters:
        CidrBlock: 10.1.0.0/16
        ProductName:
          Ref: ProductName
        Env:
          Ref: Env
        Name:
          Fn::Sub: vpc-${Env}
  PublicSubnetA:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-northeast-1.amazonaws.com/cfn-template-myproduct-dev/network/58522c022c5bda06695b2b6418c62347.template
      Parameters:
        VPC:
          Fn::GetAtt:
          - VPC
          - Outputs.VpcId
        CidrBlock: 10.1.0.0/24
        AZ: 0
        ProductName:
          Ref: ProductName
        Env:
          Ref: Env
        Name:
          Fn::Sub: public-subnet-a-${Env}
  PublicSubnetC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-northeast-1.amazonaws.com/cfn-template-myproduct-dev/network/58522c022c5bda06695b2b6418c62347.template
      Parameters:
        VPC:
          Fn::GetAtt:
          - VPC
          - Outputs.VpcId
        CidrBlock: 10.1.1.0/24
        AZ: 2
        ProductName:
          Ref: ProductName
        Env:
          Ref: Env
        Name:
          Fn::Sub: public-subnet-c-${Env}
  PrivateSubnetA:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-northeast-1.amazonaws.com/cfn-template-myproduct-dev/network/58522c022c5bda06695b2b6418c62347.template
      Parameters:
        VPC:
          Fn::GetAtt:
          - VPC
          - Outputs.VpcId
        CidrBlock: 10.1.8.0/24
        AZ: 0
        ProductName:
          Ref: ProductName
        Env:
          Ref: Env
        Name:
          Fn::Sub: private-subnet-a-${Env}
  PrivateSubnetC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-northeast-1.amazonaws.com/cfn-template-myproduct-dev/network/58522c022c5bda06695b2b6418c62347.template
      Parameters:
        VPC:
          Fn::GetAtt:
          - VPC
          - Outputs.VpcId
        CidrBlock: 10.1.9.0/24
        AZ: 2
        ProductName:
          Ref: ProductName
        Env:
          Ref: Env
        Name:
          Fn::Sub: private-subnet-c-${Env}
  PrivateSubnetAForDB:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-northeast-1.amazonaws.com/cfn-template-myproduct-dev/network/58522c022c5bda06695b2b6418c62347.template
      Parameters:
        VPC:
          Fn::GetAtt:
          - VPC
          - Outputs.VpcId
        CidrBlock: 10.1.16.0/24
        AZ: 0
        ProductName:
          Ref: ProductName
        Env:
          Ref: Env
        Name:
          Fn::Sub: private-subnet-a-db-${Env}
  PrivateSubnetCForDB:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-northeast-1.amazonaws.com/cfn-template-myproduct-dev/network/58522c022c5bda06695b2b6418c62347.template
      Parameters:
        VPC:
          Fn::GetAtt:
          - VPC
          - Outputs.VpcId
        CidrBlock: 10.1.17.0/24
        AZ: 1
        ProductName:
          Ref: ProductName
        Env:
          Ref: Env
        Name:
          Fn::Sub: private-subnet-c-db-${Env}
  PublicSubnetAForCloud9:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-northeast-1.amazonaws.com/cfn-template-myproduct-dev/network/58522c022c5bda06695b2b6418c62347.template
      Parameters:
        VPC:
          Fn::GetAtt:
          - VPC
          - Outputs.VpcId
        CidrBlock: 10.1.240.0/24
        AZ: 0
        ProductName:
          Ref: ProductName
        Env:
          Ref: Env
        Name:
          Fn::Sub: private-subnet-a-cloud9-${Env}
  PublicSubnetCForCloud9:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-northeast-1.amazonaws.com/cfn-template-myproduct-dev/network/58522c022c5bda06695b2b6418c62347.template
      Parameters:
        VPC:
          Fn::GetAtt:
          - VPC
          - Outputs.VpcId
        CidrBlock: 10.1.241.0/24
        AZ: 1
        ProductName:
          Ref: ProductName
        Env:
          Ref: Env
        Name:
          Fn::Sub: private-subnet-a-cloud9-${Env}
  PrivateSubnetAForVPCEndpoint:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-northeast-1.amazonaws.com/cfn-template-myproduct-dev/network/58522c022c5bda06695b2b6418c62347.template
      Parameters:
        VPC:
          Fn::GetAtt:
          - VPC
          - Outputs.VpcId
        CidrBlock: 10.1.248.0/24
        AZ: 0
        ProductName:
          Ref: ProductName
        Env:
          Ref: Env
        Name:
          Fn::Sub: private-subnet-a-vpcendpoint-${Env}
  PrivateSubnetCForVPCEndpoint:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-northeast-1.amazonaws.com/cfn-template-myproduct-dev/network/58522c022c5bda06695b2b6418c62347.template
      Parameters:
        VPC:
          Fn::GetAtt:
          - VPC
          - Outputs.VpcId
        CidrBlock: 10.1.249.0/24
        AZ: 1
        ProductName:
          Ref: ProductName
        Env:
          Ref: Env
        Name:
          Fn::Sub: private-subnet-c-vpcendpoint-${Env}
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: ProductName
        Value:
          Ref: ProductName
      - Key: Env
        Value:
          Ref: Env
      - Key: Name
        Value:
          Fn::Sub: internet-gateway-${Env}
  GatewayAttachement:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Fn::GetAtt:
        - VPC
        - Outputs.VpcId
      InternetGatewayId:
        Ref: InternetGateway
  PublicRouteTable:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-northeast-1.amazonaws.com/cfn-template-myproduct-dev/network/843d3694e89bdf405398c2f338273784.template
      Parameters:
        VPC:
          Fn::GetAtt:
          - VPC
          - Outputs.VpcId
        ProductName:
          Ref: ProductName
        Env:
          Ref: Env
        Name:
          Fn::Sub: public-route-table-${Env}
  PublicRoute:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-northeast-1.amazonaws.com/cfn-template-myproduct-dev/network/30f3cea1220ce60a41c53ca8e5f3d32f.template
      Parameters:
        RouteTableId:
          Fn::GetAtt:
          - PublicRouteTable
          - Outputs.RouteTable
        GatewayId:
          Ref: InternetGateway
        NatGatewayId: ''
  PublicSubnetARouteTableAssociation:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-northeast-1.amazonaws.com/cfn-template-myproduct-dev/network/9faaf1b362a9c4d938f2b9f67342040b.template
      Parameters:
        SubnetId:
          Fn::GetAtt:
          - PublicSubnetA
          - Outputs.SubnetId
        RouteTableId:
          Fn::GetAtt:
          - PublicRouteTable
          - Outputs.RouteTable
  PublicSubnetCRouteTableAssociation:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-northeast-1.amazonaws.com/cfn-template-myproduct-dev/network/9faaf1b362a9c4d938f2b9f67342040b.template
      Parameters:
        SubnetId:
          Fn::GetAtt:
          - PublicSubnetC
          - Outputs.SubnetId
        RouteTableId:
          Fn::GetAtt:
          - PublicRouteTable
          - Outputs.RouteTable
Outputs:
  VPC:
    Value:
      Fn::GetAtt:
      - VPC
      - Outputs.VpcId
    Export:
      Name: VPC
  PublicSubnetA:
    Value:
      Fn::GetAtt:
      - PublicSubnetA
      - Outputs.SubnetId
    Export:
      Name: PublicSubnetA
  PublicSubnetC:
    Value:
      Fn::GetAtt:
      - PublicSubnetC
      - Outputs.SubnetId
    Export:
      Name: PublicSubnetC
  PrivateSubnetA:
    Value:
      Fn::GetAtt:
      - PrivateSubnetA
      - Outputs.SubnetId
    Export:
      Name: PrivateSubnetA
  PrivateSubnetC:
    Value:
      Fn::GetAtt:
      - PrivateSubnetC
      - Outputs.SubnetId
    Export:
      Name: PrivateSubnetC
  PrivateSubnetAForDB:
    Value:
      Fn::GetAtt:
      - PrivateSubnetAForDB
      - Outputs.SubnetId
    Export:
      Name: PrivateSubnetAForDB
  PrivateSubnetCForDB:
    Value:
      Fn::GetAtt:
      - PrivateSubnetCForDB
      - Outputs.SubnetId
    Export:
      Name: PrivateSubnetCForDB
  PublicSubnetAForCloud9:
    Value:
      Fn::GetAtt:
      - PublicSubnetAForCloud9
      - Outputs.SubnetId
    Export:
      Name: PublicSubnetAForCloud9
  PublicSubnetCForCloud9:
    Value:
      Fn::GetAtt:
      - PublicSubnetCForCloud9
      - Outputs.SubnetId
    Export:
      Name: PublicSubnetCForCloud9
  PrivateSubnetAForVPCEndpoint:
    Value:
      Fn::GetAtt:
      - PrivateSubnetAForVPCEndpoint
      - Outputs.SubnetId
    Export:
      Name: PrivateSubnetAForVPCEndpoint
  PrivateSubnetCForVPCEndpoint:
    Value:
      Fn::GetAtt:
      - PrivateSubnetCForVPCEndpoint
      - Outputs.SubnetId
    Export:
      Name: PrivateSubnetCForVPCEndpoint
