AWSTemplateFormatVersion: '2010-09-09'
Description: "VPC,Subnet,NATGateway,RouteTable\n"
Parameters:
  ProductName:
    Type: String
  Env:
    Type: String
    AllowedValues:
    - dev
    - stg
    - prd
Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-northeast-1.amazonaws.com/cfn-template-myproduct-dev/network/d5c108ffe5580c8236bf83c932cff09c.template
      Parameters:
        CidrBlock: 10.1.0.0/16
        ProductName:
          Ref: ProductName
        Env:
          Ref: Env
  PublicSubnetA:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-northeast-1.amazonaws.com/cfn-template-myproduct-dev/network/709be9f6ec1e7e5bf443e39fa2df6f3e.template
      Parameters:
        VPC:
          Fn::GetAtt:
          - VPC
          - Outputs.VpcId
        CidrBlock: 10.1.0.0/24
        AZ: 0
        ProductName:
          Ref: ProductName
        Env:
          Ref: Env
  PublicSubnetC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-northeast-1.amazonaws.com/cfn-template-myproduct-dev/network/709be9f6ec1e7e5bf443e39fa2df6f3e.template
      Parameters:
        VPC:
          Fn::GetAtt:
          - VPC
          - Outputs.VpcId
        CidrBlock: 10.1.1.0/24
        AZ: 2
        ProductName:
          Ref: ProductName
        Env:
          Ref: Env
  PrivateSubnetA:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-northeast-1.amazonaws.com/cfn-template-myproduct-dev/network/709be9f6ec1e7e5bf443e39fa2df6f3e.template
      Parameters:
        VPC:
          Fn::GetAtt:
          - VPC
          - Outputs.VpcId
        CidrBlock: 10.1.8.0/24
        AZ: 0
        ProductName:
          Ref: ProductName
        Env:
          Ref: Env
  PrivateSubnetC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-northeast-1.amazonaws.com/cfn-template-myproduct-dev/network/709be9f6ec1e7e5bf443e39fa2df6f3e.template
      Parameters:
        VPC:
          Fn::GetAtt:
          - VPC
          - Outputs.VpcId
        CidrBlock: 10.1.9.0/24
        AZ: 2
        ProductName:
          Ref: ProductName
        Env:
          Ref: Env
  PrivateSubnetAForDB:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-northeast-1.amazonaws.com/cfn-template-myproduct-dev/network/709be9f6ec1e7e5bf443e39fa2df6f3e.template
      Parameters:
        VPC:
          Fn::GetAtt:
          - VPC
          - Outputs.VpcId
        CidrBlock: 10.1.16.0/24
        AZ: 0
        ProductName:
          Ref: ProductName
        Env:
          Ref: Env
  PrivateSubnetCForDB:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-northeast-1.amazonaws.com/cfn-template-myproduct-dev/network/709be9f6ec1e7e5bf443e39fa2df6f3e.template
      Parameters:
        VPC:
          Fn::GetAtt:
          - VPC
          - Outputs.VpcId
        CidrBlock: 10.1.17.0/24
        AZ: 1
        ProductName:
          Ref: ProductName
        Env:
          Ref: Env
  PublicSubnetAForBastion:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-northeast-1.amazonaws.com/cfn-template-myproduct-dev/network/709be9f6ec1e7e5bf443e39fa2df6f3e.template
      Parameters:
        VPC:
          Fn::GetAtt:
          - VPC
          - Outputs.VpcId
        CidrBlock: 10.1.240.0/24
        AZ: 0
        ProductName:
          Ref: ProductName
        Env:
          Ref: Env
  PublicSubnetCForBastion:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-northeast-1.amazonaws.com/cfn-template-myproduct-dev/network/709be9f6ec1e7e5bf443e39fa2df6f3e.template
      Parameters:
        VPC:
          Fn::GetAtt:
          - VPC
          - Outputs.VpcId
        CidrBlock: 10.1.241.0/24
        AZ: 1
        ProductName:
          Ref: ProductName
        Env:
          Ref: Env
  PrivateSubnetAForVPCEndpoint:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-northeast-1.amazonaws.com/cfn-template-myproduct-dev/network/709be9f6ec1e7e5bf443e39fa2df6f3e.template
      Parameters:
        VPC:
          Fn::GetAtt:
          - VPC
          - Outputs.VpcId
        CidrBlock: 10.1.248.0/24
        AZ: 0
        ProductName:
          Ref: ProductName
        Env:
          Ref: Env
  PrivateSubnetCForVPCEndpoint:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-northeast-1.amazonaws.com/cfn-template-myproduct-dev/network/709be9f6ec1e7e5bf443e39fa2df6f3e.template
      Parameters:
        VPC:
          Fn::GetAtt:
          - VPC
          - Outputs.VpcId
        CidrBlock: 10.1.249.0/24
        AZ: 1
        ProductName:
          Ref: ProductName
        Env:
          Ref: Env
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: ProductName
        Value:
          Ref: ProductName
      - Key: Env
        Value:
          Ref: Env
  GatewayAttachement:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Fn::GetAtt:
        - VPC
        - Outputs.VpcId
      InternetGatewayId:
        Ref: InternetGateway
  PublicRouteTable:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-northeast-1.amazonaws.com/cfn-template-myproduct-dev/network/7fc042774ee153c2d11356ffda33a93b.template
      Parameters:
        VPC:
          Fn::GetAtt:
          - VPC
          - Outputs.VpcId
        ProductName:
          Ref: ProductName
        Env:
          Ref: Env
  PublicRoute:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-northeast-1.amazonaws.com/cfn-template-myproduct-dev/network/30f3cea1220ce60a41c53ca8e5f3d32f.template
      Parameters:
        RouteTableId:
          Fn::GetAtt:
          - PublicRouteTable
          - Outputs.RouteTable
        GatewayId:
          Ref: InternetGateway
        NatGatewayId: ''
  PublicSubnetARouteTableAssociation:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-northeast-1.amazonaws.com/cfn-template-myproduct-dev/network/ff3df38d2a58071823a48e6ec930c455.template
      Parameters:
        SubnetId:
          Fn::GetAtt:
          - PublicSubnetA
          - Outputs.SubnetId
        RouteTableId:
          Fn::GetAtt:
          - PublicRouteTable
          - Outputs.RouteTable
        ProductName:
          Ref: ProductName
        Env:
          Ref: Env
  PublicSubnetCRouteTableAssociation:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-northeast-1.amazonaws.com/cfn-template-myproduct-dev/network/ff3df38d2a58071823a48e6ec930c455.template
      Parameters:
        SubnetId:
          Fn::GetAtt:
          - PublicSubnetC
          - Outputs.SubnetId
        RouteTableId:
          Fn::GetAtt:
          - PublicRouteTable
          - Outputs.RouteTable
        ProductName:
          Ref: ProductName
        Env:
          Ref: Env
Outputs:
  VPC:
    Value:
      Fn::GetAtt:
      - VPC
      - Outputs.VpcId
    Export:
      Name: VPC
  PublicSubnetA:
    Value:
      Fn::GetAtt:
      - PublicSubnetA
      - Outputs.SubnetId
    Export:
      Name: PublicSubnetA
  PublicSubnetC:
    Value:
      Fn::GetAtt:
      - PublicSubnetC
      - Outputs.SubnetId
    Export:
      Name: PublicSubnetC
  PrivateSubnetA:
    Value:
      Fn::GetAtt:
      - PrivateSubnetA
      - Outputs.SubnetId
    Export:
      Name: PrivateSubnetA
  PrivateSubnetC:
    Value:
      Fn::GetAtt:
      - PrivateSubnetC
      - Outputs.SubnetId
    Export:
      Name: PrivateSubnetC
  PrivateSubnetAForDB:
    Value:
      Fn::GetAtt:
      - PrivateSubnetAForDB
      - Outputs.SubnetId
    Export:
      Name: PrivateSubnetAForDB
  PrivateSubnetCForDB:
    Value:
      Fn::GetAtt:
      - PrivateSubnetCForDB
      - Outputs.SubnetId
    Export:
      Name: PrivateSubnetCForDB
  PublicSubnetAForBastion:
    Value:
      Fn::GetAtt:
      - PublicSubnetAForBastion
      - Outputs.SubnetId
    Export:
      Name: PublicSubnetAForBastion
  PublicSubnetCForBastion:
    Value:
      Fn::GetAtt:
      - PublicSubnetCForBastion
      - Outputs.SubnetId
    Export:
      Name: PublicSubnetCForBastion
  PrivateSubnetAForVPCEndpoint:
    Value:
      Fn::GetAtt:
      - PrivateSubnetAForVPCEndpoint
      - Outputs.SubnetId
    Export:
      Name: PrivateSubnetAForVPCEndpoint
  PrivateSubnetCForVPCEndpoint:
    Value:
      Fn::GetAtt:
      - PrivateSubnetCForVPCEndpoint
      - Outputs.SubnetId
    Export:
      Name: PrivateSubnetCForVPCEndpoint
