AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  ProductName:
    Type: String
  Env:
    Type: String
    AllowedValues:
      - dev
      - stg
      - prd

  Scheme:
    Type: String
  Subnets:
    Type: CommaDelimitedList
  SecurityGroups:
    Type: CommaDelimitedList

Resources:
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    DeletionPolicy: Delete # FIXME: DEV環境とそれ以外で分岐
    Properties:
      Scheme: !Ref Scheme
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: 30
        - Key: deletion_protection.enabled
          Value: false # FIXME: DEV環境とそれ以外で分岐
#        - Key: access_logs.s3.enabled
#          Value: true
#        - Key: access_logs.s3.bucket
#          Value: !Sub ${ProjectName}-public-load-balancer-log # TODO: バケット作成
      Subnets: !Ref Subnets
      SecurityGroups: !Ref SecurityGroups
      Tags:
        - Key: 'ProductName'
          Value: !Ref ProductName
        - Key: 'Env'
          Value: !Ref Env

Outputs:
  LoadBalancerArn:
    Value: !Ref LoadBalancer
  LoadBalancerDnsName:
    Value: !GetAtt LoadBalancer.DNSName
