AWSTemplateFormatVersion: '2010-09-09'
Description: >
  ECSCluster,Service,Task,LoadBalancer,SecurityGroup

Parameters:
  ProductName:
    Type: String
  Env:
    Type: String
    AllowedValues:
      - dev
      - stg
      - prd

  #########################################
  # Parameters For ECS
  #########################################
  ImageUrl:
    Type: String
    Default: '743530693495.dkr.ecr.ap-northeast-1.amazonaws.com/fight'
  ContainerPort:
    Type: Number
    Default: 8080
  ContainerCpu:
    Type: Number
    Default: 256
  ContainerMemory:
    Type: Number
    Default: 512
  DesiredCount:
    Type: Number
    Default: 2

Resources:
  #########################################
  # ECS Cluster
  #########################################
  ECSCluster:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: '../../../templates/ecs/cluster.yml'
      Parameters:
        ProductName: !Ref ProductName
        Env: !Ref Env

  #########################################
  # ECS Task
  #########################################
  ECSTask:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: '../../../templates/ecs/task.yml'
      Parameters:
        ContainerCpu: !Ref ContainerCpu
        ContainerMemory: !Ref ContainerMemory
        ImageUrl: !Ref ImageUrl
        ContainerPort: !Ref ContainerPort
        ExecutionRoleArn: !Ref ECSTaskExecutionRole
        ProductName: !Ref ProductName
        Env: !Ref Env

  #########################################
  # ECS Service
  #########################################
  ECSService:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - ECSCluster
      - ECSTask
    Properties:
      TemplateURL: '../../../templates/ecs/service.yml'
      Parameters:
        ClusterArn: !GetAtt ECSCluster.Outputs.ECSClusterArn
        DesiredCount: !Ref DesiredCount
        SecurityGroups: !Join [ ',', [!ImportValue ECSContainerSecurityGroup] ]
        Subnets: !Join [ ',', [!ImportValue PrivateSubnetA, !ImportValue PrivateSubnetC] ]
        TaskDefinitionArn: !GetAtt ECSTask.Outputs.TaskDefinitionArn
        ContainerPort: !Ref ContainerPort
        TargetGroupArn: !ImportValue TargetGroupForECS
        ProductName: !Ref ProductName
        Env: !Ref Env

  #########################################
  # IAM
  #########################################

  # This is an IAM role which authorizes ECS to manage resources on your
  # account on your behalf, such as updating your load balancer with the
  # details of where your containers are, so that traffic can reach your
  # containers.
  ECSRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: [ecs.amazonaws.com]
            Action: ['sts:AssumeRole']
      Path: /
      Policies:
        - PolicyName: ecs-service
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  # Rules which allow ECS to attach network interfaces to instances
                  # on your behalf in order for awsvpc networking mode to work right
                  - 'ec2:AttachNetworkInterface'
                  - 'ec2:CreateNetworkInterface'
                  - 'ec2:CreateNetworkInterfacePermission'
                  - 'ec2:DeleteNetworkInterface'
                  - 'ec2:DeleteNetworkInterfacePermission'
                  - 'ec2:Describe*'
                  - 'ec2:DetachNetworkInterface'
                  # Rules which allow ECS to update load balancers on your behalf
                  # with the information sabout how to send traffic to your containers
                  - 'elasticloadbalancing:DeregisterInstancesFromLoadBalancer'
                  - 'elasticloadbalancing:DeregisterTargets'
                  - 'elasticloadbalancing:Describe*'
                  - 'elasticloadbalancing:RegisterInstancesWithLoadBalancer'
                  - 'elasticloadbalancing:RegisterTargets'
                Resource: '*'
  # This is a role which is used by the ECS tasks themselves.
  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: [ecs-tasks.amazonaws.com]
            Action: ['sts:AssumeRole']
      Path: /
      Policies:
        - PolicyName: AmazonECSTaskExecutionRolePolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  # Allow the ECS Tasks to download images from ECR
                  - 'ecr:GetAuthorizationToken'
                  - 'ecr:BatchCheckLayerAvailability'
                  - 'ecr:GetDownloadUrlForLayer'
                  - 'ecr:BatchGetImage'
                  # Allow the ECS tasks to upload logs to CloudWatch
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: '*'
