AWSTemplateFormatVersion: '2010-09-09'
Description: >
  codecommit with code

Resources:
  CodeCommitRepository:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: fight
      RepositoryDescription: fight-repository
      Code:
        BranchName: main
        S3:
          Bucket: fight-codecommit-dev
          Key: fight.zip
