AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  GroupId:
    Type: String
  CidrIp:
    Type: String
  CidrIpv6:
    Type: String
  FromPort:
    Type: String
  ToPort:
    Type: String

Conditions:
  isEmptyCidrIp: !Equals [ !Ref CidrIp, '' ]
  isEmptyCidrIpv6: !Equals [ !Ref CidrIpv6, '' ]

Resources:
  # IPv4かIPv6のいずれかしか単一でしか指定できない
  SecurityGroupIngressCidrIp:
    Condition: isEmptyCidrIpv6
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: !Ref AWS::StackName
      GroupId: !Ref GroupId
      CidrIp: !Ref CidrIp
      IpProtocol: tcp
      FromPort: !Ref FromPort
      ToPort: !Ref ToPort
  SecurityGroupIngressCidrIpv6:
    Condition: isEmptyCidrIp
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: !Ref AWS::StackName
      GroupId: !Ref GroupId
      CidrIpv6: !Ref CidrIpv6
      IpProtocol: tcp
      FromPort: !Ref FromPort
      ToPort: !Ref ToPort

Outputs:
  SecurityGroupIngressCidrIp:
    Value: !Ref SecurityGroupIngressCidrIp
  SecurityGroupIngressCidrIpv6:
    Value: !Ref SecurityGroupIngressCidrIpv6
