AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  ProductName:
    Type: String
  Env:
    Type: String
    AllowedValues:
      - dev
      - stg
      - prd

  SubnetId:
    Type: String

Resources:
  NatGatewayAttachment:
    Type: AWS::EC2::EIP
    DeletionPolicy: Delete # FIXME: DEV環境とそれ以外で分岐
    Properties:
      Domain: vpc
  NatGateway:
    Type: AWS::EC2::NatGateway
    DeletionPolicy: Delete # FIXME: DEV環境とそれ以外で分岐
    Properties:
      AllocationId: !GetAtt NatGatewayAttachment.AllocationId
      SubnetId: !Ref SubnetId

Outputs:
  NatGateway:
    Value: !Ref NatGateway
