AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  ProductName:
    Type: String
  Env:
    Type: String
    AllowedValues:
      - dev
      - stg
      - prd
  Name:
    Type: String

  SubnetId:
    Type: String

Resources:
  NatGatewayAttachment:
    Type: AWS::EC2::EIP
    DeletionPolicy: Delete # FIXME: DEV環境とそれ以外で分岐
    Properties:
      Domain: vpc
      Tags:
        - Key: 'ProductName'
          Value: !Ref ProductName
        - Key: 'Env'
          Value: !Ref Env
        - Key: 'Name'
          Value: !Ref Name

  NatGateway:
    Type: AWS::EC2::NatGateway
    DeletionPolicy: Delete # FIXME: DEV環境とそれ以外で分岐
    Properties:
      AllocationId: !GetAtt NatGatewayAttachment.AllocationId
      SubnetId: !Ref SubnetId
      Tags:
        - Key: 'ProductName'
          Value: !Ref ProductName
        - Key: 'Env'
          Value: !Ref Env
        - Key: 'Name'
          Value: !Ref Name

Outputs:
  NatGateway:
    Value: !Ref NatGateway
