AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  SubnetId:
    Type: String
  RouteTableId:
    Type: String

Resources:
  RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref SubnetId
      RouteTableId: !Ref RouteTableId
