AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  RouteTableId:
    Type: String
  GatewayId:
    Type: String
  NatGatewayId:
    Type: String

Conditions:
  isEmptyGatewayId: !Equals [ !Ref GatewayId, '' ]
  isEmptyNatGatewayId: !Equals [ !Ref NatGatewayId, '' ]

Resources:
  Route:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref RouteTableId
      DestinationCidrBlock: '0.0.0.0/0'
      GatewayId: !If [ isEmptyGatewayId, !Ref AWS::NoValue, !Ref GatewayId ]
      NatGatewayId: !If [ isEmptyNatGatewayId, !Ref AWS::NoValue, !Ref NatGatewayId ]

Outputs:
  Route:
    Value: !Ref Route
