AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  ProductName:
    Type: String
  Env:
    Type: String
    AllowedValues:
      - dev
      - stg
      - prd
  Name:
    Type: String

  VPC:
    Type: String

Resources:
  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: 'ProductName'
          Value: !Ref ProductName
        - Key: 'Env'
          Value: !Ref Env
        - Key: 'Name'
          Value: !Ref Name

Outputs:
  RouteTable:
    Value: !Ref RouteTable
