AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  ProductName:
    Type: String
  Env:
    Type: String
    AllowedValues:
      - dev
      - stg
      - prd

  VPC:
    Type: String

Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    DeletionPolicy: Delete # FIXME: DEV環境とそれ以外で分岐
    Properties:
      GroupDescription: !Ref AWS::StackName
      VpcId: !Ref VPC
      Tags:
        - Key: 'ProductName'
          Value: !Ref ProductName
        - Key: 'Env'
          Value: !Ref Env

Outputs:
  SecurityGroupId:
    Value: !GetAtt SecurityGroup.GroupId
