AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  ProductName:
    Type: String
  Env:
    Type: String
    AllowedValues:
      - dev
      - stg
      - prd
  Name:
    Type: String

  VPC:
    Type: String
  CidrBlock:
    Type: String
  AZ:
    Type: String

Resources:
  Subnet:
    Type: AWS::EC2::Subnet
    DeletionPolicy: Delete # FIXME: DEV環境とそれ以外で分岐
    Properties:
      AvailabilityZone:
        Fn::Select:
          - !Ref AZ
          - Fn::GetAZs: {Ref: 'AWS::Region'}
      VpcId: !Ref VPC
      CidrBlock: !Ref CidrBlock
      Tags:
        - Key: 'ProductName'
          Value: !Ref ProductName
        - Key: 'Env'
          Value: !Ref Env
        - Key: 'Name'
          Value: !Ref Name


Outputs:
  SubnetId:
    Value: !Ref Subnet
