AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  ProductName:
    Type: String
  Env:
    Type: String
    AllowedValues:
      - dev
      - stg
      - prd
  Name:
    Type: String

  CidrBlock:
    Type: String

Resources:
  VPC:
    Type: AWS::EC2::VPC
    DeletionPolicy: Delete # FIXME: DEV環境とそれ以外で分岐
    Properties:
      EnableDnsSupport: true
      EnableDnsHostnames: true
      CidrBlock: !Ref CidrBlock
      Tags:
        - Key: 'ProductName'
          Value: !Ref ProductName
        - Key: 'Env'
          Value: !Ref Env
        - Key: 'Name'
          Value: !Ref Name

Outputs:
  VpcId:
    Value: !Ref VPC
  CidrBlock:
    Value: !GetAtt VPC.CidrBlock
