AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ProductName:
    Type: String
  Env:
    Type: String
    AllowedValues:
      - dev
      - stg
      - prd


Resources:
  Cloud9:
    Type: AWS::Cloud9::EnvironmentEC2
    Properties:
      AutomaticStopTimeMinutes: 30
      ConnectionType: CONNECT_SSH
      InstanceType: t2.micro
      Name: !Sub
        - ${ProjectName}-${Env}-cloud9
        - {ProjectName: !Ref ProjectName, EnvType: !Ref Env}
      Description: !Sub
        - ${ProjectName}-${Env}-cloud9
        - {ProjectName: !Ref ProjectName, EnvType: !Ref Env}
      SubnetId:
        Fn::ImportValue: !Sub
          - ${ProjectName}-${Env}-public-subnet1
          - {ProjectName: !Ref ProjectName, Env: !Ref Env}
      Tags:
        - Key: 'ProductName'
          Value: !Ref ProductName
        - Key: 'Env'
          Value: !Ref Env

# Outputs:
