AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ProductName:
    Type: String
  Env:
    Type: String
    AllowedValues:
      - dev
      - stg
      - prd

Resources:
  Cloud9:
    Type: AWS::Cloud9::EnvironmentEC2
    DeletionPolicy: Delete
    Properties:
      AutomaticStopTimeMinutes: 30
      # ConnectionType: CONNECT_SSH
      InstanceType: t2.micro
      Name: !Sub ${ProductName}-bastion-${Env}
      SubnetId: !ImportValue PublicSubnetAForCloud9
      Tags:
        - Key: 'ProductName'
          Value: !Ref ProductName
        - Key: 'Env'
          Value: !Ref Env

# Outputs:
