AWSTemplateFormatVersion: '2010-09-09'
Description: "ECSCluster,Service,Task,LoadBalancer,SecurityGroup\n"
Parameters:
  ProductName:
    Type: String
  Env:
    Type: String
    AllowedValues:
    - dev
    - stg
    - prd
Resources:
  DBSubnetGroup:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-northeast-1.amazonaws.com/cfn-template-myproduct-dev/backend-rds/fc585bc37c741b4e57eaf391b85694da.template
      Parameters:
        SubnetIds:
          Fn::Join:
          - ','
          - - Fn::ImportValue: PrivateSubnetAForDB
            - Fn::ImportValue: PrivateSubnetCForDB
        ProductName:
          Ref: ProductName
        Env:
          Ref: Env
        Name:
          Fn::Sub: ${ProductName}-db-subnet-group-${Env}
  ResourceDBCluster:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-northeast-1.amazonaws.com/cfn-template-myproduct-dev/backend-rds/60a9a295bc2eacefefa0e803816564af.template
      Parameters:
        VpcSecurityGroupIds:
          Fn::Join:
          - ','
          - - Fn::ImportValue: DBSecurityGroup
        DBSubnetGroup:
          Fn::GetAtt:
          - DBSubnetGroup
          - Outputs.DBSubnetGroupId
        DBSecret:
          Fn::GetAtt:
          - RDBSecrets
          - Outputs.SecretId
        ProductName:
          Ref: ProductName
        Env:
          Ref: Env
        Name:
          Fn::Sub: ${ProductName}-resource-db-${Env}
  RDBSecrets:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-northeast-1.amazonaws.com/cfn-template-myproduct-dev/backend-rds/c1717fa9b487ff351c8409d18f39e6b5.template
      Parameters:
        ProductName:
          Ref: ProductName
        Env:
          Ref: Env
        Name:
          Fn::Sub: ${ProductName}-rdb1-${Env}
  RDBSecretsRotate:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-northeast-1.amazonaws.com/cfn-template-myproduct-dev/backend-rds/e1e196c31e96b35b04c88ddd8fddf0be.template
      Parameters:
        SecretId:
          Fn::GetAtt:
          - RDBSecrets
          - Outputs.SecretId
        AutomaticallyAfterDays: 1
        Duration: 1h
  RDBSecretsAttachment:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-northeast-1.amazonaws.com/cfn-template-myproduct-dev/backend-rds/62b1008f77a687baf88d2d3c9eb99769.template
      Parameters:
        SecretId:
          Fn::GetAtt:
          - RDBSecrets
          - Outputs.SecretId
        TargetId:
          Fn::GetAtt:
          - ResourceDBCluster
          - Outputs.DBClusterId
