AWSTemplateFormatVersion: 2010-09-09
Description: >
  for codecommit

Parameters:
  Env:
    Type: String
    Default: dev
    AllowedValues:
      - dev
    Description: Environment

Mappings:
  EnvironmentMap:
    dev:
      BucketName: fight-codecommit-dev

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      Tags:
        - Key: ProjectName
          Value: fight
      BucketName: !FindInMap [ EnvironmentMap, !Ref Env, BucketName]
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
#      LifecycleConfiguration:
#        Rules:
#          - ExpirationInDays: 7
#            Id: 7DaysLifeCycleRule
#            Status: Enabled
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !FindInMap [ EnvironmentMap, !Ref Env, BucketName ]
      PolicyDocument:
        Statement:
          Action: "s3:*"
          Effect: Allow
          Resource: !Join
            - ""
            - - "arn:aws:s3:::"
              - !FindInMap [ EnvironmentMap, !Ref Env, BucketName ]
              - "/*"
          Principal:
            Service: "codecommit.amazonaws.com"
